#if !macro
// Give access to ceramic shortcuts: app, screen, settings, log...
// Also provide statically typed asset identifiers: Images.XXX, Fonts.ROBOTO_MEDIUM_MEDIUM...
import assets.*;
import ceramic.Shortcuts.*;
#end
